name: GitHub Actions Demo
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  React-Project:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "14"
      - run: npm install
      - run: npm run lint
      - uses: akhileshns/heroku-deploy@v3.12.12 
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: "react-pokemon-app-1"
          heroku_email: ${{secrets.HEROKU_EMAIL}}
